from enum import Enum

class AlertType(str, Enum):
    TEMPLATE_APPROVED = "TEMPLATE_APPROVED"
    TEMPLATE_REJECTED = "TEMPLATE_REJECTED"
    UNREAD_THRESHOLD = "UNREAD_THRESHOLD"
    WABA_DISCONNECTED = "WABA_DISCONNECTED"
    CAMPAIGN_FAILED = "CAMPAIGN_FAILED"
